### ISSUE TITLE
svwsconfig.json in Docker Umgebung

### ISSUE THREAD

**Issue by SimonFrank14** [SVWS-NRW/SVWS-Server#276]
Ich habe in meiner Docker Installation die svwsconfig.json von extern gemountet, damit die Einstellungen nicht beim Neuerstellen des Containers verloren gehen. (Das könnte man ggf. auch noch in der Doku ergänzen.) In der Doku steht, dass beim Anlegen von neuen Schemata über die Admin UI diese in der config Datei ergänzt werden. Leider ist das bei mir in dem beschriebenen Setup nicht passiert. Ich habe hier nur das aus der Docker Compose und den Umgebungsvariablen generierte Schema in der Config Datei.

**Comment by FPfotenhauer** [comment]
Wie wird das volume denn in den Container eingebunden?

```
    volumes:
      - ./svwsconfig.json:/etc/app/svws/conf/
```

**Comment by SimonFrank14** [comment]
Ich habe es in das Root Verzeichnis vom Container gemountet, wo die Config Datei lag. Muss die in das Conf Verzeichnis? Das müsste ich dann mal testen. Ich komme gerade nicht ans Cluster und kann nicht in die Dateien rein schauen, die ich vom Volume aus rein reiche. 

```yaml
services:
  mariadb:
    restart: always
    image: mariadb:10.7.3
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "${MariaDB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${MariaDB_DATABASE}"
      MARIADB_USER: "${MariaDB_USER}"
      MARIADB_PASSWORD: "${MariaDB_PASSWORD}"
    networks:
      - schild-internal
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MariaDB_USER --password=$$MariaDB_PASSWORD
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 2m
    volumes:
      - /var/data/schild/db:/var/lib/mysql

  svws-server:
    image: svwsnrw/svws-server:latest
    depends_on:
      - mariadb
    ports:
      - "8444:8443"
    environment:
      MariaDB_HOST: "${MariaDB_HOST}"
      MariaDB_ROOT_PASSWORD: "${MariaDB_ROOT_PASSWORD}"
      MariaDB_DATABASE: "${MariaDB_DATABASE}"
      MariaDB_USER: "${MariaDB_USER}"
      MariaDB_PASSWORD: "${MariaDB_PASSWORD}"
      SVWS_TLS_KEY_ALIAS: "${SVWS_TLS_KEY_ALIAS}"
      SVWS_TLS_KEYSTORE_PATH: "${SVWS_TLS_KEYSTORE_PATH}"
      SVWS_TLS_KEYSTORE_PASSWORD: "${SVWS_TLS_KEYSTORE_PASSWORD}"
    networks:
      - schild-internal
    volumes:
      - /var/data/schild/init-scripts:/etc/app/svws/init-scripts
      - /var/data/schild/config/svwsconfig.json:/opt/app/svws/svwsconfig.json
      - /var/data/schild/keystore:/etc/app/svws/conf/keystore/

networks:
  schild-internal:
    driver: overlay
 ```
