### ISSUE TITLE
SVWS Server in Docker (Container Manager) auf Synology NAS svwsconfig-template.json wird fehlerhaft verarbeitet)

### ISSUE THREAD

**Issue by mscoe19** [SVWS-NRW/SVWS-Server#362]
Bei der Installation mittels Docker Compose mit der folgenden compose.yml **(Edit 24.03.2025: compose.yml angepasst, damit auch die MariaDB-Daten persistieren bei einem Recreate, unten in Reply)**

```
services:
    mariadb:
        image: mariadb:latest
        restart: always
        ports:
            - 3306:3306
        environment:
            - MARIADB_ROOT_PASSWORD=xxxxxxxxx
            - MARIADB_DATABASE=svwsdb
            - MARIADB_USER=svwsadmin
            - MARIADB_PASSWORD=yyyyyyyyyy
            - MARIADB_DATA_DIR=/var/lib/mysql/data
            - MARIADB_LOG_DIR=/var/lib/mysql/log
        volumes:
            - /volume1/DockerData/MariaDB/data:/var/lib/mysql/data
            - /volume1/DockerData/MariaDB/logs:/var/lib/mysql/log
            - /volume1/DockerData/MariaDB/conf:/etc/mysql
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            start_period: 10s
            interval: 10s
            timeout: 5s
            retries: 3
        networks:
            - svws-net

    svws-server:
        image: svwsnrw/svws-server:latest
        depends_on:
            mariadb:
                condition: service_healthy
        ports:
            - 8443:8443
        environment:
            - MARIADB_HOST=mariadb
            - MARIADB_ROOT_PASSWORD=xxxxxxxxxxxxxxxxxxxxxx
            - MARIADB_DATABASE=svwsdb
            - MARIADB_USER=svwsadmin
            - MARIADB_PASSWORD=yyyyyyyyyyyyyyyyyy
            - INIT_SCRIPTS_DIR=/opt/app/svws/init-scripts
            - SVWS_TLS_KEYSTORE_PATH=/etc/app/svws/conf/keystore
            - SVWS_CONF_DIR=/etc/app/svws/conf
            - SVWS_TLS_KEYSTORE_PASSWORD=zzzzzzzzzzzzzzzzzzz
            - SVWS_TLS_KEY_ALIAS=svws-key
            - SVWS_TLS_KEYSTORE_CREATE=false
        volumes:
            - /volume1/DockerData/SVWS/init-scripts:/opt/app/svws/init-scripts
            - /volume1/DockerData/SVWS/conf/keystore:/etc/app/svws/conf/keystore
            - /volume1/DockerData/SVWS/conf:/etc/app/svws/conf
        networks:
            - svws-net
networks:
    svws-net:
        driver: bridge

```
schlägt der Start des svws-Servers zunächst fehl, weil die zur automatischen Konfiguration des Containers benutzte Datei

deployment/docker/svws/conf/svwsconfig-template.json

```
"DBKonfiguration" : {
    "dbms" : "MARIA_DB",
    "location" : "${MariaDB_HOST}",
    "defaultschema" : "${MariaDB_DATABASE}",
    "SchemaKonfiguration" : [ {
      "name" : "${MariaDB_DATABASE}",
      "svwslogin" : false,
      "username" : "${MariaDB_USER}",
      "password" : "${MariaDB_PASSWORD}"
```
die environment-Variablen teil in Kleinbuchstaben enthält, die offiziellen env-Variablen des MariaDB-Images aber komplett in Großbuchstaben sind.
Das müsste geändert werden, dann läuft das automatische Deployment mittels docker compose, sonst nicht.
So, wie es jetzt ist, wird die Datenbank nicht korrekt eingerichtet.
