### ISSUE TITLE
Docker Compose file in Default Konfiguration nicht lauffähig

### ISSUE THREAD

**Issue by sknopp** [SVWS-NRW/SVWS-Server#398]
Hallo,

gerade starte ich mit der technischen Evaluation der Migration nach Schild 3 und setze in dem Rahmen den SVWS-Server auf.

Vorneweg: Ich finde es richtig gut, dass es endlich einen richtigen Backend API-Server nach "allen Regeln der Kunst" gibt!

Umgebung:
Blankes Ubuntu Server 24.04 inkl. Docker im schulinternen Netzwerk.

Installation nach [Dokumentation](https://doku.svws-nrw.de/deployment/Docker/#svws-umgebung-mit-docker-compose-starten).

Ich habe einen Java Truststore mit dem SSL-Zertifikat der Schule erfolgreich importiert, das Frontend wird korrekt mit gültigem SSL-Zertifikat gehostet. Ansonsten habe ich bis auf das Setzen der `TESTDB_PASSWORD` Env-Variable und der Umleitung von Container-Port 8443 auf Host-Port 443 nichts weiter geändert. Sprich auch das Init-Skript mit den Testdaten läuft mit.

ich habe folgenden Docker Log Output:

Docker Compose Log: [compose.log](https://github.com/user-attachments/files/20539973/compose.log)

<details>
<summary>docker-compose.yml</summary>

```yaml
version: "5"
services:
  mariadb:
    restart: always
    image: mariadb:10.7.3
    environment:
      MARIADB_ROOT_PASSWORD: "${MariaDB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${MariaDB_DATABASE}"
      MARIADB_USER: "${MariaDB_USER}"
      MARIADB_PASSWORD: "${MariaDB_PASSWORD}"
    ports:
      - "3306:3306"
    env_file:
      - .env
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MariaDB_USER --password=$$MariaDB_PASSWORD
      interval: 1s
      timeout: 5s
      retries: 10

  svws-server:
    image: svwsnrw/svws-server:latest
    depends_on:
      mariadb:
        condition: service_healthy
    links:
      - mariadb
    ports:
      - "443:8443"
    environment:
      MariaDB_HOST: "${MariaDB_HOST}"
      MariaDB_ROOT_PASSWORD: "${MariaDB_ROOT_PASSWORD}"
      MariaDB_DATABASE: "${MariaDB_DATABASE}"
      MariaDB_USER: "${MariaDB_USER}"
      MariaDB_PASSWORD: "${MariaDB_PASSWORD}"
      SVWS_TLS_KEY_ALIAS: "${SVWS_TLS_KEY_ALIAS}"
      SVWS_TLS_KEYSTORE_PATH: "${SVWS_TLS_KEYSTORE_PATH}"
      SVWS_TLS_KEYSTORE_PASSWORD: "${SVWS_TLS_KEYSTORE_PASSWORD}"
    volumes:
      - ./init-scripts:/etc/app/svws/init-scripts
      - ./keystore:/etc/app/svws/conf/keystore/
    env_file:
      - .env
```

</details>

Die `.env` Datei:

```ini
INIT_SCRIPTS_DIR=/etc/app/svws/init-scripts
TESTDB_PASSWORD=your-testdb-pw
MariaDB_ROOT_PASSWORD=test
MariaDB_DATABASE=gymabi
MariaDB_HOST=mariadb
MariaDB_USER=test
MariaDB_PASSWORD=test
SVWS_TLS_KEYSTORE_PASSWORD=test123
SVWS_TLS_KEY_ALIAS=alias1
SVWS_TLS_KEYSTORE_PATH=/etc/app/svws/conf/keystore
```

Im Frontend zeigt sich folgendes Bild:

<img width="1483" alt="Image" src="https://github.com/user-attachments/assets/f26ecc8b-36dc-4f2e-accb-e1e202be41bb" />

Meine Interpretation von außen ist, dass der Server beim anfänglichen Integrationscheck probiert im mysql-Schema zu agieren, obwohl die eigenen Datensätze dort garnicht liegen. Der Import der Daten durch das Initskript lief problemlos und ich habe die Daten in der Datenbank bereits mit einem SQLClient betrachten können.

Was kann ich tun um das Setup zum laufen zu bekommen?

Vielen Dank schonmal.

**Comment by kroerig** [comment]
Bitte mal das komplette Log vom Start an hier anhängen.
Am besten den Stack vorher einmal löschen.

Und auch mal das Docker-compose File und die .evn-Datei posten.

**Comment by FPfotenhauer** [comment]
Der Server hat ein Schema "mysql" in der svwsconfig.json stehen. 
Das würde ich löschen und einen anderen Namen wählen.

Was wurde den in der .ENV für ein Name für die Datenbank gewählt?

**Comment by sknopp** [comment]
Ich habe die Angaben gemäß euren Nachfragen oben aktualisiert. @FPfotenhauer ich kann keine svwsconfig.json im Projekt finden. Kannst du verlinken welche Datei genau du meinst?

Schönen Sonntag!

**Comment by kroerig** [comment]
Ja, ich hole die Datei mit einem Bind-Mount in den Container. Siehe https://github.com/SVWS-NRW/SVWS-Server/pull/157

Zusätzlich leite ich auch das Logs-Verzeichnis noch um, damit die für die Fehlersuche auch erhalten bleiben.

```
      - ./logs:/opt/app/svws/logs
      - ./svwsconfig.json:/opt/app/svws/svwsconfig.json
```
Allerdings ist da noch ein kleiner Haken drin: Die Zeile darf erst hinzugefügt werden, nachdem der Server die Datei initial erstellt hat und man sie sich aus dem Container geholt hat. Ich schaue gerade noch ob ich das irgendwie eleganter hinbekomme.

BTW: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion

**Comment by kroerig** [comment]
Kommando zurück. Ich hatte gerade eine Eingebung. Da war doch was: https://github.com/SVWS-NRW/SVWS-Server/issues/362

Der Fehler liegt in der im ZIP Archiv mitgelieferten `.env`. Die Variblennamen müssen in Großbuchstaben geschrieben werden dann passt es auch.

```
INIT_SCRIPTS_DIR=/etc/app/svws/init-scripts

MARIADB_ROOT_PASSWORD=test
MARIADB_DATABASE=gymabi
MARIADB_HOST=mariadb
MARIADB_USER=test
MARIADB_PASSWORD=test

SVWS_TLS_KEYSTORE_PASSWORD=test123
SVWS_TLS_KEY_ALIAS=alias1
SVWS_TLS_KEYSTORE_PATH=/etc/app/svws/conf/keystore
SVWS_TLS_KEYSTORE_CREATE=true
```

und dazu passend dann die _docker-compose.yml_:
```
services:
  mariadb:
    restart: always
    image: mariadb:10.7.3
    environment:
      MARIADB_HOST: "${MARIADB_HOST}"
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${MARIADB_DATABASE}"
      MARIADB_USER: "${MARIADB_USER}"
      MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
    env_file:
      - .env
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MARIADB_USER --password=$$MARIADB_PASSWORD
      interval: 1s
      timeout: 5s
      retries: 10

  svws-server:
    image: svwsnrw/svws-server:latest
    depends_on:
      mariadb:
        condition: service_healthy
    links:
      - mariadb
    ports:
      - "8443:8443"
    environment:
      MARIADB_HOST: "${MARIADB_HOST}"
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${MARIADB_DATABASE}"
      MARIADB_USER: "${MARIADB_USER}"
      MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
    volumes:
      - ./logs:/opt/app/svws/logs
#      - ./svwsconfig.json:/opt/app/svws/svwsconfig.json
      - ./volume/keystore:/etc/app/svws/keystore
      - ./init-scripts:/etc/app/svws/init-scripts
    env_file:
      - .env

```

und noch ein angepasstes _import-test-db.sh_:

```
#!/bin/bash

CURRENT_SCRIPT=$(readlink -f "$0")
CURRENT_DIR=$(dirname "$CURRENT_SCRIPT")

# Testdatenbanken von github als zip-File herunterladen
echo "Lade Testdatenbanken herunter ..."
wget https://github.com/SVWS-NRW/SVWS-TestMDBs/archive/refs/heads/main.zip -O $CURRENT_DIR/databases.zip -o /dev/null

# Access-Datenbanken aus den heruntergeladenen zip-File extrahieren
echo "Extrahiere Access-Datenbanken ..."
unzip $CURRENT_DIR/databases.zip -d $CURRENT_DIR/databases "*.mdb"
rm -rf $CURRENT_DIR/databases.zip

# Import (MigrateDB) der Access-Datenbank(en) durchführen ...
MDBFILE="$CURRENT_DIR/databases/SVWS-TestMDBs-main/GOST_Abitur/Abi-Test-Daten-01/GymAbi.mdb"
echo "Importiere Datenbank: ${MDBFILE} ..."
java -cp "svws-server-app-*.jar:./*:./lib/*" de.svws_nrw.db.utils.app.MigrateDB -j -r -1 -sd "MDB" \
   -sl "${MDBFILE}" \
   -td "MARIA_DB" \
   -tl ${MARIADB_HOST} \
   -ts ${MARIADB_DATABASE} \
   -tu ${MARIADB_USER} \
   -tp ${MARIADB_PASSWORD} \
   -tr ${MARIADB_ROOT_PASSWORD}

# Aufräumen
rm -rf $CURRENT_DIR/databases

```
Ich hoffe, ich habe alle Stellen gefunden.
